In [19]:
import numpy as np

def LU(A):
    U = np.copy(A).astype('float32')
    m, n = A.shape
    L = np.eye(n).astype('float32')
    for k in range(n-1):
        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] -= L[j,k] * U[k,k:n]
    return L, U

Next we define in-place LU factorization.

In [26]:
def LU_inplace(A):
    A = A.astype('float32')
    m, n = A.shape
    for k in range(n-1):
        for j in range(k+1,n):
            A[j,k] = A[j,k]/A[k,k]
            A[j,(k+1):n] -= A[j,k] * A[k,(k+1):n]
    return A

Both of these functions allow us to compute the LU factorization. However, where the first creates and stores in memory two matrices, L and U, the second function stores the two matrices in the previously allocated memory address for the input matrix. The ones for L do not need to be stored, they are assumed. Do not use this if you still have use for your input matrix after computing the decomposition.

In [32]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

L, U = LU(x)
print(U)
print(L)


[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  0.]]
[[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]


In [33]:
A = LU_inplace(x)
print(A)

[[ 1.  2.  3.]
 [ 4. -3. -6.]
 [ 7.  2.  0.]]


We see that this holds the same information as the original function outputs.